# Neural Networks for Language Processing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Създаване на DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}


In [4]:
df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


In [5]:
data = np.array([1, 2, 3, 4, 5])
print(np.mean(data))  # Средно аритметично
print(np.median(data))  # Медиана
print(np.std(data))  # Стандартно отклонение


3.0
3.0
1.4142135623730951


In [7]:

array = np.array([1, 2, 3, 4])
# Индексиране
print(array[0])  # Първият елемент
print(array[-1]) # Последният елемент

# Срезове
print(array[:2])  # Първите два елемента

1
4
[1 2]


In [11]:
matrix = np.array([[1, 2], [3, 4]])
matrix[0][1]

2

In [12]:
# Основни операции
array = np.array([1, 2, 3])
print(array + 1)  # Добавяне към всеки елемент
print(array * 2)  # Умножение на всеки елемент


[2 3 4]
[2 4 6]


In [24]:
df[df['Age'] == 25]

Name  Age
0  Alice   25

In [27]:
# Групиране по колона и намиране на средно аритметично
grouped = df.groupby('Name')['Age'].mean()
print(grouped)

Name
Alice      25.0
Bob        30.0
Charlie    35.0
Name: Age, dtype: float64


In [28]:
# Добавяне на нова колона
df['Salary'] = [50000, 60000, 70000]
print(df)


      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000


In [29]:
# Премахване на колона
df = df.drop(columns=['Salary'])
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


In [31]:
data = {
    'Name': ['Alice', 'Bob', 'Alice', 'Bob', 'Alice', 'Charlie'],
    'Age': [25, 30, 35, 40, 30, 50]
}

df = pd.DataFrame(data)
df

Name  Age
0    Alice   25
1      Bob   30
2    Alice   35
3      Bob   40
4    Alice   30
5  Charlie   50

In [37]:
df.groupby('Name')['Age'].mean()

Name
Alice      30.0
Bob        35.0
Charlie    50.0
Name: Age, dtype: float64

In [47]:
df[df['Age'] > 25]

Name  Age
1      Bob   30
2    Alice   35
3      Bob   40
4    Alice   30
5  Charlie   50

In [49]:
data = {
    'Name': ['Alice', 'Bob', 'Alice', 'Charlie'],
    'Age': [25, 30, 35, 50],
    'City': ['Sofia', 'Plovdiv', 'Varna', 'Burgas']
}

df = pd.DataFrame(data)
df

Name  Age     City
0    Alice   25    Sofia
1      Bob   30  Plovdiv
2    Alice   35    Varna
3  Charlie   50   Burgas

In [54]:
df[df['Name'] == 'Bob'][['Age', 'City']]

Age     City
1   30  Plovdiv

In [57]:
df[(df['Name'] == 'Bob') & (df['Age'] == 30)]

Name  Age     City
1  Bob   30  Plovdiv

In [59]:
a_list = list("abcdefg")
a_list

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [62]:
numpy_array = np.arange(1, 10)
numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
array = np.arange(1, 101)
array.mean()

50.5

In [75]:
print(np.mean(array))
print(np.median(array))
print(np.std(array))

np.sum(array[array % 2 == 0])

50.5
50.5
28.86607004772212


2550

In [76]:
array = np.arange(1, 101)
mean = np.mean(array)
even_sum = np.sum(array[array % 2 == 0])

print("Средно аритметично:", mean)
print("Сума на четни числа:", even_sum)

Средно аритметично: 50.5
Сума на четни числа: 2550


In [78]:
df['Salary'] = [5000, 6000, 7000, 8000]

In [81]:
df['Tax'] = df['Salary']  * 0.2

In [82]:
df

Name  Age     City  Salary     Tax
0    Alice   25    Sofia    5000  1000.0
1      Bob   30  Plovdiv    6000  1200.0
2    Alice   35    Varna    7000  1400.0
3  Charlie   50   Burgas    8000  1600.0

In [83]:
df['Salary'].mean()

6500.0

In [92]:
# Двумерен масив (матрица)
b = np.array([[1, 2, 3, 7, 1], [4, 5, 6, 4, -1]])
b

array([[ 1,  2,  3,  7,  1],
       [ 4,  5,  6,  4, -1]])

In [93]:
max_index = b.argmax()
min_index = b.argmin()

In [128]:
min_index
print(np.argmax(b))
new_arr = np.add(b, np.array([2, 2, 2, 2, 2]))

3


In [129]:
column_add = np.add(b, np.array([2, 2, 2, 2, 2]))
print(column_add)

[[ 5  6  7 11  5]
 [ 8  9 10  8  3]]


In [110]:
linspace = np.linspace(0, 1, 5)

In [130]:
linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [114]:
linspace[:2 :2]

array([0.])

In [131]:
arr = np.array([1, 2, 3])
new_arr = np.append(arr, [4, 5, 6])

print(new_arr)

[1 2 3 4 5 6]


In [135]:
c = np.append(b, [2, 2, 2, 2, 2])

In [136]:
c

array([3, 4, 5, 9, 3, 6, 7, 8, 6, 1, 2, 2, 2, 2, 2])